
= Timelab ADEM project

image::https://api.travis-ci.org/timelab/ADEM.svg[alt="Build Status", link="https://travis-ci.org/timelab/ADEM", align="left", float]

The http://www.timelab.org/[Timelab] ADEM project enables cyclists to measure particulate matter (PM~1~ and PM~2.5~). The quality based on these measurements are displayed on the device, temporarily stored and sent via WiFi to a central data collection service.

The aim of this project is to create a low-cost open-source DIY hardware and firmware kit that is modular and adjustable, can be locally reproduced and repaired.

This git repository hosts the hardware designs, firmware and technical documentation for the ADEM device. You can find the documentation at: https://github.com/timelab/ADEM/tree/master/docs[]

More information related to this project is available from the project's wiki at: http://wiki.timelab.org/wiki/A.D.E.M[]

We welcome feedback and contributions.

image::http://timelab.github.io/ADEM-Logos/svg/adem_logo-txt_stroke.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right", float]
