= Arduino setup

The firmware is written in Arduino.


== Installing the ESP8266 Arduino Addon

Follow the SparkFun tutorial on how to install the ESP8266 to your Arduino IDE:
https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/installing-the-esp8266-arduino-addon


== Cloning the ADEM GitHub repository


=== Installing Git

- Sign-up for a GitHub account at https://github.com/[]

- Install git on your PC

    - for Debian/Ubuntu:

    $ sudo apt-get install git

    - for Fedora/RHEL/CentOS:

    $ sudo yum install git

- Set your GitHub and e-mailadress

    $ git config --global user.name "John Doe"
    $ git config --global user.email johndoe@example.com


=== Cloning the repository

You can make a local copy of the ADEM project code by running the following git command:

    $ git clone git@github.com:timelab/ADEM.git

If you have a login, you can fork the project to your GitHub profile, and add it as a separate remote in _.git/config_.
This way you can create pull-requests by modifying your local copy and pushing it to your personal GitHub profile.
The GitHub web-interface than proposes to create a pull-request. It helps if you use different branches for pushing changes.

More information regarding the use of Git is available from: http://www.git-scm.com/book/en/v1/Git-Basics

More information regarding the use of GitHub is available from: https://guides.github.com/activities/hello-world/A

=== Git daily use

Show the status of your repository:

    $ git status

Edit the files in you local copy with your editor of choice. After creating a new file or folder, add it so git can start tracking it:

    $ git add GITHUB

Remove a file (also from the repository after commit!)

    $ git rm HITGUB

Commit your changes to your local copy:

    $ git commit --all --message "Added new file with info on GitHub use."

Now upload it to the online repository:

    $ git push

What has happenend:

    $ git log

Get the changes from the online repository and merge them into local files

    $ git pull --rebase


== Build the firmware

=== Installing required libraries in Arduino

In order to build project code using Arduino Sketch IDE, you need to ensure that Arduino can find the libraries we use.

On Linux and MacOS/X you can do this with the following command:

   $ cd /path/to/git/clone/ADEM
   $ ln -sf "$PWD/libraries/"* ~/Arduino/libraries/


=== Using make for building Arduino code

The project also provides a Makefile with the instructions to build, flash/upload and monitor the device.

In order to do that, you first have to ensure that the Makefile can find your Arduino installation and local .arduino15 directory. We use a symlink for this.

On Linux you can do this

  $ cd /path/to/git/clone/ADEM
  $ ln -sf "/path/to/your/arduino-1.6.8" ./Arduino
  $ ln -sf ~"/.arduino15" ./arduino15

On MacOSX you can do the following:

  $ cd /path/to/git/clone/ADEM
  $ ln -sf "/path/to/your/Arduino 1.6.8.app/Contents/Java" ./Arduino
  $ ln -sf ~"/Library/Arduino15" ./arduino15

Now you can start building the source code by doing:

  $ make

You can also build other test code by doing something like:

  $ make SKETCH=people/dagwieers/gps_test/gps_test.ino

Once this is done, you can flash your device using:

  $ make flash

You can do both in one go by using the `upload` target, just like in the Arduino Sketch IDE:

  $ make upload

or

  $ make upload SKETCH=people/dagwieers/gps_test/gps_test.ino

You can also influence the serial port and baud rate used for flashing:

  $ make upload SERIAL_PORT=/dev/ttyUSB0 FLASH_BAUD=115200

The default serial port for flashing is `/dev/ttyUSB0` and the default baud rate for flashing is `921600`.


=== Connecting to the device

The most "stable" way to connect to your device is unfortunately still using the Serial Monitor of the Arduino Sketch IDE. This has something to do with the serial port initialization and baud rate. Once the port is initialized (at 74880), you can usually switch to using this:

  $ make monitor

or:

  $ make serial

The first command is using the GNU screen tool for connecting to the device, and this enables also sending characters to the device. The second command is a simple `cat` to your device. You can influence the device and baud rate using:

  $ make monitor SERIAL_PORT=/dev/ttyUSB0 SERIAL_BAUD=74880

The default serial port for monitoring is `/dev/ttyUSB0` and the default baud rate for monitoring is `38400`.


=== Building with DEBUG enabled

We also provide a way to enable debugging for your build.

  $ make CFLAGS=-DDEBUG

This incidentally is also the default compilation flag. However some libraries have their own debugging flag.

  $ make CFLAGS="-DDEBUG_SCHED -DDEBUG_GPS"

If you want to build without DEBUG mode, you can simply do:

  $ make CFLAGS=


=== Building with DEMO mode

There is a demonstration mode that is enabled by doing:

  $ make CFLAGS="-DDEMO"


== External libraries

All external libraries we depend upon for the firmware are included in the repository. This to ensure that we have reproducible builds and can integrate easily with Travis CI. Hence there is no need to download them separately.

The following external libraries are currently being used:

Adafruit NeoPixel::
  - Version: 1.0.6
  - License: LGPL v3
  - URL: https://github.com/adafruit/Adafruit_NeoPixel

ArduinoJson::
  - Version: 5.6.5
  - License: MIT
  - URL: https://github.com/bblanchon/ArduinoJson

espsoftwareserial::
  - Version: 1.0
  - License: LGPL v2.1
  - URL: https://github.com/plerup/espsoftwareserial

TinyGPS++::
  - Version: 0.94b
  - License: LGPL v2.1
  - URL: https://github.com/mikalhart/TinyGPSPlus

WiFiManager::
  - Version: 0.12
  - License: MIT
  - URL: https://github.com/tzapu/WiFiManager

image::http://timelab.github.io/ADEM-Logos/svg/adem_logo-txt_stroke.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right", float]
