= Arduino setup

The firmware is written in Arduino.

== Installing the ESP8266 Arduino Addon

Follow the SparkFun tutorial on how to install the ESP8266 to your Arduino IDE:
https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/installing-the-esp8266-arduino-addon

== Cloning the ADEM GitHub repository

=== Installing Git

- Sign-up for a GitHub account at https://github.com/[]

- Install git on your PC

    - for Debian/Ubuntu:

    $ sudo apt-get install git

    - for Fedora/RHEL/CentOS:

    $ sudo yum install git

    - For Windows:

    Download and install from https://git-scm.com/downloads
    If you are editing code, make sure that your editor or IDE does not modify line-endings (this would make it look like unmodified files have been changed, and/or results in extra newlines under Linux).
    JetBrains IntelliJ IDEA is an example of a multi-platform IDE which can work with github, and provide structure to the codebase.

- Set your GitHub and e-mailadress

    $ git config --global user.name "John Doe"
    $ git config --global user.email johndoe@example.com

=== Cloning the repository

You can make a local copy of the ADEM project code by running the following git command:

    $ git clone git@github.com:timelab/ADEM.git

== Contributing code

=== Forking
If you have a github account, you can contribute code to the ADEM project. Go to https://github.com/timelab/ADEM and *fork* the project to your GitHub profile. Then add it as a separate remote (stored in _.git/config_).

    $ git remote add --mirror=fetch yourname https://github.com/yourgitusername/ADEM

If you use SSH keys, use:
    $ git remote add --mirror=fetch yourname git@github.com:yourgitusername/ADEM.git

Update:
    $ git remote update

This way you can create pull-requests by modifying your local copy and pushing it to your personal GitHub profile.
Afterwards, the GitHub web-interface proposes to create a pull-request. It helps if you use different branches for pushing changes.

More information regarding the use of Git is available from: http://www.git-scm.com/book/en/v1/Git-Basics
The forking and contributing aspect is handled on: https://www.git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

More information regarding the use of GitHub is available from: https://guides.github.com/activities/hello-world/

=== Git daily use

Show the status of your local repository, you can do this any time:

    $ git status

When you want to add or change code, *make a new branch first*:

    $ git checkout -b <name of your branch>

Edit the files in you local copy with your editor of choice. After creating a new file or folder, add it so git can start tracking it:

    $ git add <file>

Remove a file (also from the repository after commit!)

    $ git rm <file>

Commit your changes to your local copy and add your commit message on the top of the file:

    $ git commit -v

Now upload (_Push_) it to your online forked Github repo:

    $ git push --set-upstream <user> <name of your branch>

Go to https://gitcom.com/timelab/ADEM and click *Compare & pull request*. If it fixes an issue, add _Fixes #issuenumber_ as comment. Click ''Create pull request''


What has happenend:

    $ git log

Get the changes from the online repository and merge them into local files

    $ git pull --rebase

== Build the firmware

=== Installing required libraries in Arduino

In order to build project code using Arduino Sketch IDE, you need to ensure that Arduino can find the libraries we use.

You will have to overwrite the Arduino "Sketchbook location" with the path to where your ADEM folder is. You can set this under File -> Preferences.
If you are already using Arduino for other projects, alternatively, you can check out the ADEM repository to a subfolder of the default Sketchbook location.

=== Using make as alternative to Arduino IDE

==== Using make for building Arduino code

The project also provides a Makefile with the instructions to build, flash/upload and monitor the device.

You can build the source code by doing:

  $ make build

You can also build the i2c-slave code (used for the GPS) by doing:

  $ make build SKETCH=i2c-slave/i2c-slave.ino

Other test code can be build as well using:

  $ make build SKETCH=people/dagwieers/gps_test/gps_test.ino

Once this is done, you can flash your device using:

  $ make flash

or

  $ make flash SKETCH=i2c-slave/i2c-slave.ino

You can do both in one go by using the `upload` target, just like in the Arduino Sketch IDE:

  $ make upload

or

  $ make upload SKETCH=i2c-slave/i2c-slave.ino

You can also influence the serial port and baud rate used for flashing:

  $ make upload SERIAL_PORT=/dev/ttyUSB0 FLASH_BAUD=115200

The default serial port for flashing depends on the HWTYPE but usually is `/dev/ttyUSB0`, the default baud rate for flashing depends on the hardware.


==== Connecting to the device

The most "stable" way to connect to your device is unfortunately still using the Serial Monitor of the Arduino Sketch IDE. This has something to do with the serial port initialization and baud rate. Once the port is initialized in the Arduino IDE (at 74880 baud), you can exit the IDE and switch to using this:

  $ make monitor

or:

  $ make serial

The first command is using the GNU screen tool for connecting to the device, and this enables also sending characters to the device. The second command is a simple `cat` to your device. You can influence the device and baud rate using:

  $ make monitor SERIAL_PORT=/dev/ttyUSB0 SERIAL_BAUD=74880

The default serial port for monitoring is `/dev/ttyUSB0` and the default baud rate for monitoring is `38400`. Use  `CTRL+a` and then `k` to exit monitor.

FIXME: apparently you can use 'tail' to monitor, if you set the the terminal line settings correctly using stty; ex. stty -F /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 cs8 74880 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
FIXME: untested with ESP8266 (tested with Arduino Nano at different baud rate)

==== Building with DEBUG enabled

We also provide a way to enable debugging for your build.

  $ make CFLAGS=-DDEBUG

This incidentally is also the default compilation flag. However some libraries have their own debugging flag.

  $ make CFLAGS="-DDEBUG_SCHED -DDEBUG_GPS"

If you want to build without DEBUG mode, you can simply do:

  $ make CFLAGS=


==== Building with DEMO mode

There is a demonstration mode that is enabled by doing:

  $ make CFLAGS="-DDEMO"


==== Building, flashing and monitoring

Now for convenience you can do building, flashing and monitoring at once:

 $ make upload monitor


== External libraries

All external libraries we depend upon for the firmware are included in the repository. This to ensure that we have reproducible builds and can integrate easily with Travis CI. Hence there is no need to download them separately.

The following external libraries are currently being used:

Adafruit NeoPixel::
  - Version: 1.0.6
  - License: LGPL v3
  - URL: https://github.com/adafruit/Adafruit_NeoPixel

ArduinoJson::
  - Version: 5.6.7
  - License: MIT
  - URL: https://github.com/bblanchon/ArduinoJson

espsoftwareserial::
  - Version: 3.1.0
  - License: LGPL v2.1+
  - URL: https://github.com/plerup/espsoftwareserial

TinyGPS++::
  - Version: 0.94b
  - License: LGPL v2.1+
  - URL: https://github.com/mikalhart/TinyGPSPlus

WiFiManager::
  - Version: 0.12
  - License: MIT
  - URL: https://github.com/tzapu/WiFiManager

image::http://timelab.github.io/ADEM-Logos/svg/adem_logo-txt_stroke.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right", float]
