= Hardware

The project uses the SparkFun ESP8266 Thing.

This ESP8266 based WiFi controller development board runs the ADEM firmware and conveniently hosts a LiPo battery management system that is key in the mobility aspect of this project. Apart from the headers for the SparkFun Thing, the project's printed circuit board has room for a GPS module, temperature and pressure sensors and connections to external parts like the PPD40NS dust sensor.

== Bill Of Materials

Listed prices are individual prices, not volume prices.

=== Mandatory components
[options="header"]
|=================================================================================================================
| Function                  | Component / Chip          | Price indication  | Datasheet / Tutorial / Info

| Microcontroller           | SparkFun ESP8266 Thing    | (15.95€ sparkfun) |
https://cdn.sparkfun.com/datasheets/Wireless/WiFi/ESP8266ThingV1.pdf[datasheet]
https://www.sparkfun.com/products/13231[link] /
https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/all[tutorial]

| Accelerometer             | GY-521 / MPU6050          | (2.83€ banggood)  |
http://store.invensense.com/datasheets/invensense/MPU-6050_DataSheet_V3%204.pdf[datasheet]
http://playground.arduino.cc/Main/MPU-6050[arduino]

| Barometer                 | BMP180                    | (2.04 € banggood) |
https://www.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf[datasheet]

| Battery                   |                           |                   |
EACHINE 3.7V 500mAh 25C

| Buzzer                    | KY-006                    | (1.44€ banggood)  |
Xinda

| Fine Dust Meter           | PPD42                     |                   |
http://sca-shinyei.com/pdf/PPD42NS.pdf[datasheet]
http://www.howmuchsnow.com/arduino/airquality/grovedust/[tutorial]

| GPS                       | XM37-1612 / GY-NEO6MV2    | (11.66€ banggood) |
https://www.iprototype.nl/docs/gps-LS20031-datasheet-gyneo6mv2.pdf[datasheet]

| Humidity + Temperature    | HTU21D                    | (4.35€ banggood)  |
https://www.adafruit.com/datasheets/1899_HTU21D.pdf[datasheet]

| RGB Led                   | NeoPixel WS2812 8xled     | (2.40€ banggood)  |
High Density Neopixel 8x LED

|=================================================================================================================

=== Optional components
[options="header"]
|=================================================================================================================
| Function                  | Component / Chip          | Price indication  | Datasheet / Tutorial / Info
| Bluethooth                | HC05 / BC417              | (4.91€ banggood)  |
https://www.olimex.com/Products/Components/RF/BLUETOOTH-SERIAL-HC-06/resources/hc06.pdf[datasheet]

| Memory I2C                | AT24C512C                 | (0.8€ digikey)    |
http://www.atmel.com/devices/AT24C512C.aspx[link]

|=================================================================================================================

image::http://ik-adem.be/wp-content/themes/adem/assets/images/adem_logo.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right"]
