= Firmware design

== Diagram

image::https://drive.google.com/file/d/0B5B2OKuFeGQfSWpKemVRNHZqeDg/view?usp=sharing[alt="Code Diagram", link="https://drive.google.com/file/d/0B5B2OKuFeGQfSFFJQkZjZVJLMGM/view?usp=sharing", align="center"]


== State machine

The state machine is part of the main loop and simply calls the specific state _loop_ code (e.g. +sleep_state()+) or handles a state transition (e.g. +start_to_sleep()+).

The current design is a simplified version, we expect additional states to be required in the future (e.g. for deep sleep, in-house measuring, etc.)


== States

These are the states the main loop controls.

 - START -> SLEEP
 - SLEEP
 - CONFIG
 - GPSTEST
 - COLLECT
 - WIFITEST
 - UPLOAD
 - RESET -> START

The conditional decisions made during a state are performed within the state _loop_. We defined specific functions for these inner loops (e.g. +sleep_state()+ or +collect_state()+).


== State transitions

Additionally when we move from one state to another state in the state machine, we require some things to happen. E.g. enable the sensors, or disconnect the GPS module. For this the state-machine will call specific _transition_ functions (e.g. +start_to_sleep()+ or +sleep_to_gpstest()+).

It is these functions that perform the most work. The state machine itself only directs to a state _loop_ or a transition _call_.

Some of these transitions do not need anything specific to happen.

=== Tasks

During the main loop, the scheduler also preserves time for other tasks to perform actions. These tasks allow e.g. the accelerator sensor to collect new data and update information that can influence the state machine.

Typically each sensor has its own task, however they may not be running the whole time but only in a specific state (e.g. COLLECT):

 - accelerator _(always enabled)_
 - barometer _(enabled in COLLECT state)_
 - gps _(enabled in GPSTEST and COLLECT state)_
 - humidity _(enabled in COLLECT state)_
 - particulate _(enabled in COLLECT state)_


== Pseudo-code

Below was our first design of the state machine. It may help in understand what is going on underneath.
Today this code is properly split into different functions and the state machine is clear an concise.

=== GLOBAL

----
Create accelerometer sensor object
Create barometer sensor object
Create buzzer object
Create gps sensor object
Create humidity sensor object
Create led object
Create particulate sensor object
Create scheduler
----


=== SETUP

----
Set STATE to START

Setup serial output

Create running accelerometer task (1s)
Create suspended barometer task (1m)
Create suspended gps task (1s)
Create suspended humidity task (1m)
Create suspended particulate task (30s)
Create suspended wifiap task
Create suspended wificlient task

Set STATE to SLEEP
----

=== LOOP

----
if STATE == SLEEP:

    if accelerometer.moving:
        Set STATE to GPS_START
        Run gps.begin
        Activate gps task

        Set STATE to GPS_TEST

    else:

        if NOT buffer.empty:
            Set STATE to WIFI_START
            Run wificlient.begin
            Activate wificlient task

            Set STATE to WIFI_TEST

        elif accelerometer.shaking:
            Set STATE to AP_START
            Run wifiap.begin
            Activate wifiap task


            Set STATE to CONFIG

elif STATE == CONFIG:

    if finished or timeout or canceled:
        Set STATE to AP_STOP
        Suspend wifiap task
        Run wifiap.end

        Set STATE to SLEEP

elif STATE == GPS_TEST:

    if accelerometer.moving:
        if gps.ready:
            Set STATE to COLLECT_START
            Run barometer.begin
            Activate barometer task
            Run humidity.begin
            Activate humidity task
            Run particulate.begin
            Activate particulate task

            Set STATE to COLLECT

    else:
        Set STATE to GPS_STOP
        Suspend barometer task
        Run barometer.end
        Suspend humidity task
        Run humidity.end
        Suspend particulate task
        Run particulate.end
        Suspend gps task
        Run gps.end

        Set STATE to SLEEP

elif STATE == COLLECT:

    Write sensor data to datastore

    if NOT accelerometer.moving or NOT gps.ready:
        Set STATE to GPS_TEST

elif STATE == WIFI_TEST:

    if wifi.fix:
        Set STATE to UPLOAD

    if accelerometer.moving OR buffer.empty or wifi.timeout:
        Set STATE to WIFI_STOP
        Suspend wificlient task
        Run wificlient.end

        Set STATE to SLEEP

elif STATE == UPLOAD:

    // Upload action finishes successfully or times out
    Create JSON of X records
    Send to Server
    Empty datastore

    Set STATE to WIFI_TEST

// LED remembers previous state and acts on state-changes
led.update()

scheduler.tick()
----

image::http://ik-adem.be/wp-content/themes/adem/assets/images/adem_logo.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right"]
