= Firmware design

== Diagram

image::https://drive.google.com/file/d/0B5B2OKuFeGQfSWpKemVRNHZqeDg/view?usp=sharing[alt="Code Diagram", link="https://drive.google.com/file/d/0B5B2OKuFeGQfSFFJQkZjZVJLMGM/view?usp=sharing", align="center"]


== States

These are the states the main loop controls.

START::
  - LED Red
  - Activate accelerometer
  - Set up serial
  - Sets up tasks
  - -> SLEEP

SLEEP::
  - LED off
  - Move to CONFIG
  - Activate gps -> GPS_TEST
  - Acticate wifi -> WIFI_TEST

CONFIG::
  - LED Yellow
  - Configure wifi-client, wifi-ap, back-end, etc. -> SLEEP

GPS_TEST::
  - LED Orange
  - -> COLLECT
  - Suspend gps -> SLEEP

COLLECT::
  - LED Green
  - Collect data
  - -> GPS_TEST

WIFI_TEST::
  - LED Purple
  - -> UPLOAD
  - Suspend wifi -> SLEEP

UPLOAD::
  - LED Blue
  - Upload data
  - Empty datastore
  - -> WIFI_TEST


=== Transition states

Additionally we have a few transition state. These are pseudo-states used for performing tasks and moving to the next state.

- AP_START
- AP_STOP
- GPS_START
- GPS_STOP
- WIFI_START
- WIFI_STOP


== Pseudo-code

=== GLOBAL

----
Create accelerometer sensor object
Create barometer sensor object
Create buzzer object
Create gps sensor object
Create humidity sensor object
Create led object
Create particulate sensor object
Create scheduler
----


=== SETUP

----
Set STATE to START

Setup serial output

Create running accelerometer task (1s)
Create suspended barometer task (1m)
Create suspended gps task (1s)
Create suspended humidity task (1m)
Create suspended particulate task (30s)
Create suspended wifiap task
Create suspended wificlient task

Set STATE to SLEEP
----

=== LOOP

----
if STATE == SLEEP:

    if accelerometer.moving:
        Set STATE to GPS_START
        Run gps.begin
        Activate gps task

        Set STATE to GPS_TEST

    else:

        if NOT buffer.empty:
            Set STATE to WIFI_START
            Run wificlient.begin
            Activate wificlient task

            Set STATE to WIFI_TEST

        elif accelerometer.shaking:
            Set STATE to AP_START
            Run wifiap.begin
            Activate wifiap task


            Set STATE to CONFIG

elif STATE == CONFIG:

    if finished or timeout or canceled:
        Set STATE to AP_STOP
        Suspend wifiap task
        Run wifiap.end

        Set STATE to SLEEP

elif STATE == GPS_TEST:

    if accelerometer.moving:
        if gps.ready:
            Set STATE to COLLECT_START
            Run barometer.begin
            Activate barometer task
            Run humidity.begin
            Activate humidity task
            Run particulate.begin
            Activate particulate task

            Set STATE to COLLECT

    else:
        Set STATE to GPS_STOP
        Suspend barometer task
        Run barometer.end
        Suspend humidity task
        Run humidity.end
        Suspend particulate task
        Run particulate.end
        Suspend gps task
        Run gps.end

        Set STATE to SLEEP

elif STATE == COLLECT:

    Write sensor data to datastore

    if NOT accelerometer.moving or NOT gps.ready:
        Set STATE to GPS_TEST

elif STATE == WIFI_TEST:

    if wifi.fix:
        Set STATE to UPLOAD

    if accelerometer.moving OR buffer.empty or wifi.timeout:
        Set STATE to WIFI_STOP
        Suspend wificlient task
        Run wificlient.end

        Set STATE to SLEEP

elif STATE == UPLOAD:

    // Upload action finishes successfully or times out
    Create JSON of X records
    Send to Server
    Empty datastore

    Set STATE to WIFI_TEST

// LED remembers previous state and acts on state-changes
led.update()

scheduler.tick()
----

image::http://ik-adem.be/wp-content/themes/adem/assets/images/adem_logo.svg[alt="ADEM logo", link="http://ik-adem.be/", align="right"]
